[project]
name = "mysql-compare"
version = "0.2.14"
requires-python = ">=3.10"
dependencies = ["mysql-connector-python==8.0.29"]

[tool.setuptools]
packages = ["mysql_compare"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
